version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysqldb
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: reservation_db
    volumes:
      - ./database/db_schema.sql:/docker-entrypoint-initdb.d/db_schema.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: shivam058/seat-reservation-backend:latest  # Change 'yourusername' to your Docker Hub username
    ports:
      - "8080:8080"
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/reservation_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: shivam058/seat-reservation-frontend:latest  # Change 'yourusername' to your Docker Hub username
    ports:
      - "3000:80"
    depends_on:
      - backend
